# Generated by Django 6.0.3 on 2026-04-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0002_interviewsession_title'),
    ]

    operations = [
    ]
