# Generated by Django 6.0.3 on 2026-04-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviews', '0003_add_token_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='InterviewMessage',
        ),
    ]
