# Generated by Codex on 2026-05-01

import django.db.models.deletion
from django.db import migrations, models


def delete_existing_sessions(apps, schema_editor):
    InterviewSession = apps.get_model('ai_interviews', 'InterviewSession')
    InterviewSession.objects.all().delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('jobs', '0001_initial'),
        ('ai_interviews', '0004_rename_message_interviewmessage'),
    ]

    operations = [
        migrations.RunPython(delete_existing_sessions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='interviewsession',
            name='job_role',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='job_posting',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='interview_sessions',
                to='jobs.jobposting',
            ),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='job_posting',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='interview_sessions',
                to='jobs.jobposting',
            ),
        ),
    ]
