# Generated by Django 6.0.3 on 2026-03-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_candidateprofile_education_employerprofile_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
