# Generated by Django 6.0.3 on 2026-04-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='employment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
