# Generated by Django 6.0.3 on 2026-04-13 22:53
# Merged with 0006 – adds employment_type with its final definition.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='employment_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('full_time', 'Full Time'),
                    ('part_time', 'Part Time'),
                    ('freelance', 'Freelance'),
                    ('internship', 'Internship'),
                    ('contract', 'Contract'),
                ],
                max_length=20,
            ),
        ),
    ]
