# Generated by Django 6.0.3 on 2026-05-07 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_workexperience_employment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='score',
        ),
    ]
