# Generated by Django 6.0.3 on 2026-04-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_workexperience_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('contract', 'Contract')], max_length=20),
        ),
    ]
