# Generated by Django 6.0.3 on 2026-05-12 01:01

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_candidateprofile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=users.models.cv_upload_path),
        ),
    ]
