# Generated by Django 6.0.3 on 2026-03-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0002_candidateprofile_education_employerprofile_skill_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('candidate', 'job')},
        ),
    ]
