services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-jobplatform}
      POSTGRES_USER: ${DB_USER:-jobplatform}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-jobplatform}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Needed so that our DB in docker doesn't get deleted
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
