# Generated by Django 6.0.3 on 2026-04-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
    ]
